import type { Metadata } from "next";
import "./globals.css";
import { helveticaNeue } from "@/app/fonts/fonts";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={helveticaNeue.variable}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
